name: Upload Images

on:
  push:
    分支:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - 名字: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - 名字: Install dependencies
        run: npm install
      - 名字: Upload images
        run: npm run upload
